name: Ultroid workflow

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    container: theteamultroid/ultroid:main

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       
       - name: Initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GH_NAME }}
           git config --global user.email ${{ secrets.GH_MAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GH_NAME }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
       - name: Running bot
         timeout-minutes: 350
         continue-on-error: true
         run: |
           git clone https://amirulandalib:${{ secrets.GH_TOKEN }}@github.com/amirulandalib/ultroid_personal /root/TeamUltroid
           cd /root/TeamUltroid
           pip install -U -r requirements.txt
           pip3 install --no-cache-dir -r requirements.txt
           pip3 install av --no-binary av
           bash startup
       - name: Loop
         continue-on-error: true
         run: |
              git clone https://github.com/${{ secrets.GH_NAME }}/ultroid-on-GH-Actions loop
              cd loop || exit 1
              echo $(TZ='${{ secrets.TZ }}' date) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop $(TZ='${{ secrets.TZ }}' date)"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_NAME }}/ultroid-on-GH-Actions HEAD:main
